on: [ pull_request, push ]

name: Test and lint

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/actions/setup-gradle@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'
    - name: Run tests
      run: ./gradlew check
