on: [ pull_request, push ]

name: Test and lint

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/gradle-build-action@v3
    - name: Run tests
      run: ./gradlew check
