on: [ pull_request, push ]

name: Test and lint

jobs:

  check:
    name: Test and lint (without RocksDB)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/actions/setup-gradle@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'
    - name: Run tests
      run: ./gradlew check

  rocksdb-check:
    name: Test and lint (with RocksDB)
    runs-on: macos-latest
    env:
      ENABLE_ROCKSDB_NATIVE: true
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/actions/setup-gradle@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'
      - name: Run tests
        run: ./gradlew check
