on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

name: Publish to Space

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/actions/setup-gradle@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'
      - name: Publish
        run: ./gradlew publishAllPublicationsToSpaceRepository
        env:
          MAVEN_SPACE_USERNAME: ${{ secrets.MAVEN_SPACE_USERNAME }}
          MAVEN_SPACE_PASSWORD: ${{ secrets.MAVEN_SPACE_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SECRET_KEY_PASSWORD: ${{ secrets.SECRET_KEY_PASSWORD }}

